development:
  adapter: postgresql
  encoding: unicode
  database: clinic_app
  pool: 2
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: clinic_app_test
  pool: 2
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: database_name
  pool: 2
  username: your_username
  password: your_password