development:
  adapter: postgresql
  encoding: unicode
  database: clinickrdb
  pool: 5
  username: clinickr
  password: clinickr
  host: clinickr_db

test:
  adapter: postgresql
  encoding: unicode
  database: clinickr_test
  pool: 5
  username: clinickr
  password: clinickr
  host: clinickr_db

production:
  adapter: postgresql
  encoding: unicode
  database: clinickr_prod
  pool: 5
  username: clinickr
  password: clinickr
  host: clinickr_db