development:
  adapter: postgresql
  encoding: unicode
  database: clinickr
  pool: 5
  username: postgres
  password: postgres
  host: 172.18.0.2

test:
  adapter: postgresql
  encoding: unicode
  database: clinickr_test
  pool: 5
  username: postgres
  password: postgres
  host: 172.18.0.2

production:
  adapter: postgresql
  encoding: unicode
  database: clinickr_prod
  pool: 5
  username: postgres
  password: postgres
  host: 172.18.0.2